// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdZwk6OweglfBh3MA2R2xeh-fepwDZajw',
    appId: '1:27457892039:web:1003ba8d908d6645da18e2',
    messagingSenderId: '27457892039',
    projectId: 'perplexity-clone-promit-1',
    authDomain: 'perplexity-clone-promit-1.firebaseapp.com',
    storageBucket: 'perplexity-clone-promit-1.firebasestorage.app',
    measurementId: 'G-E201R2QHKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmnnzsJ7a-J0VMsVFDILV5sTH10IvO8UY',
    appId: '1:27457892039:android:0efd8e9906981a49da18e2',
    messagingSenderId: '27457892039',
    projectId: 'perplexity-clone-promit-1',
    storageBucket: 'perplexity-clone-promit-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEZ1CvmhGjSnCxiaYKQnilBzEnTrmVLME',
    appId: '1:27457892039:ios:055b17c9b90e0677da18e2',
    messagingSenderId: '27457892039',
    projectId: 'perplexity-clone-promit-1',
    storageBucket: 'perplexity-clone-promit-1.firebasestorage.app',
    iosClientId: '27457892039-5ekjrl61i4e3lngqjc6ne9djsdej8e80.apps.googleusercontent.com',
    iosBundleId: 'com.example.perplexityClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEZ1CvmhGjSnCxiaYKQnilBzEnTrmVLME',
    appId: '1:27457892039:ios:055b17c9b90e0677da18e2',
    messagingSenderId: '27457892039',
    projectId: 'perplexity-clone-promit-1',
    storageBucket: 'perplexity-clone-promit-1.firebasestorage.app',
    iosClientId: '27457892039-5ekjrl61i4e3lngqjc6ne9djsdej8e80.apps.googleusercontent.com',
    iosBundleId: 'com.example.perplexityClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdZwk6OweglfBh3MA2R2xeh-fepwDZajw',
    appId: '1:27457892039:web:be8e9619d0452322da18e2',
    messagingSenderId: '27457892039',
    projectId: 'perplexity-clone-promit-1',
    authDomain: 'perplexity-clone-promit-1.firebaseapp.com',
    storageBucket: 'perplexity-clone-promit-1.firebasestorage.app',
    measurementId: 'G-TVVHN1FTWW',
  );

}